# Generated by Django 5.0.6 on 2024-06-06 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlipCoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('heads', 'Орел'), ('tails', 'Решка')], max_length=5)),
                ('flip_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
